version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Inspecting directory before packaging..."
      - ls -la
      - zip -r function.zip .
  post_build:
    commands:
      - echo "Deploying directly to AWS Lambda..."
      - aws lambda update-function-code --function-name nextchapter-storygraph-import-worker --zip-file fileb://function.zip
      - echo "Deployment complete."
