Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: nextchapter-storygraph-import
